# Generated by Django 2.2.17 on 2020-12-16 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20201216_1535'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='saleproduct',
            options={},
        ),
        migrations.AlterField(
            model_name='saleproduct',
            name='amount',
            field=models.PositiveIntegerField(),
        ),
    ]
