# Generated by Django 2.2.17 on 2020-12-16 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20201216_1546'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='saleproduct',
            options={'verbose_name': 'Produto da compra', 'verbose_name_plural': 'Produtos da compra'},
        ),
    ]
